http:
  server_port: 8123
  cors_allowed_origins:
    - "*"
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0

automation:
  - trigger:
      platform: webhook
      webhook_id: "secretdata"
    action:
      - service: persistent_notification.create
        data:
          title: "Webhook Triggered"
          message: "The webhook was accessed!"

