services:
  incrementer1:
    container_name: incrementer1
    build: ./incrementer_1
    volumes:
      - ./answers:/app/answers
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "/app/increment_1.py"]

  incrementer2:
    container_name: incrementer2
    build: ./incrementer_2
    volumes:
      - ./answers:/app/answers
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "/app/increment_2.py"]

