services:
  sender:
    container_name: sender
    build: ./sender
    volumes:
      - ./answers:/app/answers
    command: ["python", "/app/send_flag.py"]

  receiver:
    container_name: receiver
    build: ./receiver
    volumes:
      - ./answers:/app/answers
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "/app/receive_flag.py"]

